name: Windows Build/Release

on:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: SampleApps/WebView2WTL.Sample/WebViewSolution.sln
  MANIFEST_FILE_PATH: SampleApps/WebView2WTL.Sample

  BUILD_CONFIGURATION: Release
  BUILD_ARTIFACT_NAME: SampleApps/WebView2WTL.Sample/x64/Release

permissions:
  contents: read

jobs:
   build:
    runs-on: windows-latest       
    steps:      
    - name: install vcpkg
      run: |
       $Env:Path += [IO.Path]::PathSeparator + $env:VCPKG_INSTALLATION_ROOT
       vcpkg version
       vcpkg.exe integrate install

    - uses: actions/checkout@v3    

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v4
      id: vcpkg
      with:
        manifest-dir: ${{ env.MANIFEST_FILE_PATH }}
        token: ${{ github.token }}
        cache-key: windows

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
       name: WebView
       path: ${{env.BUILD_ARTIFACT_NAME}}