# clean the cache : gh cache delete --all --repo dev-advocacy/WebView2      

name: Windows Build/Release

on:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: SampleApps/WebView2WTL.Sample/WebViewSolution.sln
  MANIFEST_FILE_PATH: SampleApps/WebView2WTL.Sample/WebView2

  BUILD_CONFIGURATION: Release
  BUILD_ARTIFACT_NAME: SampleApps/WebView2WTL.Sample/x64/Release

permissions:
  contents: read

jobs:
   build:
    runs-on: windows-latest     
    timeout-minutes: 45
    steps:      

    - uses: actions/checkout@v3
  
    # - name: Cache Build
    #   uses: actions/cache@v3
    #   with:
    #       path: build
    #       key: ${{ matrix.os }}-${{ matrix.EVENT_MATRIX }}-v4   

    - name : vcpkb build
      uses: johnwason/vcpkg-action@v6
      id : vcpkg
      with:
        manifest-dir: SampleApps/WebView2WTL.Sample
        triplet: x64-windows-release
        token: ${{ github.token }}
        github-binarycache: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
       name: WebView
       path: ${{env.BUILD_ARTIFACT_NAME}}

